language: php

php:
  - 7.0

mysql:
  database: journal_cms
  username: root
  encoding: utf8

before_install:
  - curl https://puli.io/installer | php
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer --verbose self-update

install:
  - composer --verbose install

before_script:
  - cp $TRAVIS_BUILD_DIR/config/travis.settings.php $TRAVIS_BUILD_DIR/config/local.settings.php
  - cd $TRAVIS_BUILD_DIR/web
  - $TRAVIS_BUILD_DIR/vendor/bin/drush site-install config_installer --account-name=admin --account-pass=admin --site-name="Journal CMS" --yes

  # Start web server.
  - $TRAVIS_BUILD_DIR/vendor/bin/drush runserver http://127.0.0.1:8080 &
  - sleep 3

  # Migrate subjects.
  - $TRAVIS_BUILD_DIR/vendor/bin/drush mi jcms_subjects_json

script:
  # Code coverage.
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p $TRAVIS_BUILD_DIR/build/logs
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit -c $TRAVIS_BUILD_DIR/phpunit.xml.dist

after_success:
  - travis_retry $TRAVIS_BUILD_DIR/vendor/bin/coveralls -v
